version: "3"
services:
  test:
    build: ./
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: typo3
